/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/common/Setting/About.vue')['default']
    Button: typeof import('./src/components/common/HoverButton/Button.vue')['default']
    General: typeof import('./src/components/common/Setting/General.vue')['default']
    GithubSite: typeof import('./src/components/custom/GithubSite.vue')['default']
    HoverButton: typeof import('./src/components/common/HoverButton/index.vue')['default']
    NaiveProvider: typeof import('./src/components/common/NaiveProvider/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCol: typeof import('naive-ui')['NCol']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NInput: typeof import('naive-ui')['NInput']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NRow: typeof import('naive-ui')['NRow']
    NSpace: typeof import('naive-ui')['NSpace']
    PromptStore: typeof import('./src/components/common/PromptStore/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/common/Setting/index.vue')['default']
    SvgIcon: typeof import('./src/components/common/SvgIcon/index.vue')['default']
    UserAvatar: typeof import('./src/components/common/UserAvatar/index.vue')['default']
  }
}
